### ISSUE TITLE
[Feature request] Option to define controls globally

### ISSUE THREAD

**Issue by Endeliyon** [hsleisink/ravib#1]
Hey Hugo, great tool. 

Would it be possible to add functionality where I can define and store information security controls? Now I place them under threats but I have to redefine the controls for every threat where that specific control is applicable. Ideally I could tie my defined controls to a threat along with an open field to describe the situation. 

Cheers, Endeliyon

**Comment by hsleisink** [comment]
I don't think I fully understand what you mean. The controls can be configured via CMS -> Measures. Both Measures administration and Threat administration allow you to connect a threat and a (mitigating) measure. What is it you seek?

The tool is in Dutch, but your question is in English. Are you Dutch? If not, how do you deal with the fact that it's a Dutch tool? Just wondering...

**Comment by Endeliyon** [comment]
Ah I totally missed the entire CMS > Risk Analysis part. I foolishly the CMS to be solely for things like settings and users. Thanks for pointing it out, that will come in handy!

Well since your readme/install and the like are all in english I assumed it to be right way to go about it. But I am Dutch yes. Though I think this tool could also be used outside of the Netherlands, I think it is very useful. If you want to add language packs functionality at some point I am willing to help translate Dutch > English.
