### ISSUE TITLE
setup was not found

### ISSUE THREAD

**Issue by san505** [hsleisink/ravib#3]
> Not Found
> The requested URL /setup was not found on this server.
debian 8 en 9 (testserver)
apache2
mysql5
php5 en 7(testserver) met xsl, gd, sql

Hallo,
Ik krijg het niet aan de praat. waarschijnlijk doe ik iets fout. als we op de ververs knop klikken wil de website naar de map setup gaan maar die bestaat niet. hij geeft ook een fout als ik de website.conf niet goed instel.
daarna moet ik de root credentials invoeren van mysql. als ik op create database klik wil hij weer naar de map setup gaan (die niet bestaat) weer met de zelfde melding.

Ik weet niet meer hoe ik nu verder moet.

**Comment by hsleisink** [comment]
Heb je url rewriting goed ingesteld?

**Comment by san505** [comment]
nee dat was ik vergeten. niet goed gelezen.... denk dat ik er nu wel uit kom. 
dank je wel!
