### ISSUE TITLE
Descriptions in newly added or updated measures don't save

### ISSUE THREAD

**Issue by Endeliyon** [hsleisink/ravib#4]
When creating a new measure or when updating a measure the description field is not saved.
The page looks like:

1. Number
2. Name
3. Description

**Threats**
List

Any values put in 3. Description do not persist upon clicking 'Save ISO measure' or 'New ISO measure'

If you have time, could you look into this?

Thanks

**Comment by hsleisink** [comment]
That description field shouldn't be there. Remove lines 57 and 58 from views/cms/measures.xslt. I'll update the file in this repository. Thanks for reporting.
