### ISSUE TITLE
[Feature request] Threat packages

### ISSUE THREAD

**Issue by Endeliyon** [hsleisink/ravib#5]
Hey, thanks for answering/fixing my last issue.
Currently I am adding a new ISO, the 27001:2017. However, the threats that are relevant are not part of the default threats. That is not a problem since one can manually add threats with Ravib, however the default threats cannot be removed per ISO. 

Is it possible to create functionality that allows one to create threats per ISO instead of having overarching threats?

**Comment by hsleisink** [comment]
No, the threats apply to all ISO standards. I've thought about having a threat-set for each measures-set, but that makes the code very complex. It's easier to install RAVIB, remove all data and add a specific threat/measure set.

**Comment by Endeliyon** [comment]
Those threats apply to the ISO 27002/27799 and NEN 7510. However, the ISO 27001 is more focused on the management of security rather than on security measures that are a results of that. Therefor I would like a different set of threats. 
Anyway, I will make use of your proposed solution and remove threats for reporting on the 27001. Thanks for answering!

**Comment by hsleisink** [comment]
That makes no sense to me. The threats are towards information, not towards the ISO standards. And the security measures (in ISO 27002) are not the result of the ISMS. The ISMS is a way to control information security, to control the implementation of the security measures.

We can discuss this on the phone if you like. Probably more easy and affective than this issue log. If you want to, send you number via the RAVIB contact page.
