### ISSUE TITLE
Threat removal/creation behaving weird

### ISSUE THREAD

**Issue by Endeliyon** [hsleisink/ravib#6]
When trying to remove '1 / 1 | Beveiligingsinbreuken als gevolg van ontbreken van coordinatie vanuit de directie.' Ravib gives the error 'Error removing threat', however no logfiles are created. When removing '56 / 10 | Kwijtraken van belangrijke kennis bij vertrek of niet beschikbaar zijn van medewerkers.' it does work. So it appears as if threats have to be removed in order. When I removed numer 56 I could not re-add it, Ravib gave the error 'Error creating threat'. Again, no logfiles where created. 
When I reverted my machine and added a new threat it worked just fine.
Could you look into this if you have the time?

Thanks in advance

**Comment by hsleisink** [comment]
Thanks for your report. I've updated controllers/cms/threats.php, models/cms/threats.php and models/cms/measures.php. Please replace those files with the new ones from Github and let me know if that solves your issue.

**Comment by Endeliyon** [comment]
Updating those files resolved the issue, thanks!
