### ISSUE TITLE
Logo in report function does not display

### ISSUE THREAD

**Issue by Endeliyon** [hsleisink/ravib#7]
Having uploaded a PNG file to the server and having pointed RAVIB to the image I expected that it would show up in the report. Unfortunately it didn't. The logs show no errors, even in debug mode. In the report the second page appears empty, without the image. I skimmed through the code but I can't really read code and I can't understand what is going wrong.

The image is located in public/files/logo.png. Am I doing something wrong? Could you investigate if it works on your installation?

**Comment by hsleisink** [comment]
In the field 'URL van logo voor in rapportage' of the case settings, you have to specify the full path to the image. Did you do that?

**Comment by Endeliyon** [comment]
Yes I did. I tried every variety that I could think of. But none seem to work. I tried the path public/files/logo.png /files/logo.png files/logo.png /var/www/html/ravib/public/files/logo.png http://127.0.0.1/files/logo.png https://127.0.0.1/files/logo.png etc but none seem to work.

**Comment by hsleisink** [comment]
Perhaps there's something odd with the image you try to include. Have you tried using other images?

**Comment by Endeliyon** [comment]
I did, various dimensions and file sizes. However none of them worked. Can you confirm that it works on your side? Because in that case the problem should be on my side.

**Comment by hsleisink** [comment]
Yes, it works on my side. You can check it our yourself: visit https://www.ravib.nl/ and use the demo-account to login (both username and password are 'demo'). Open an existing demo case or create one and use the RAVIB logo (https://www.ravib.nl/images/layout/ravib_logo.png) for in the report.

**Comment by Endeliyon** [comment]
The problem was with http(s). Resolved.
